name: binary_types
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary type are set of classes that allows access the binary data in "C" language way.
homepage: https://github.com/mezoni/binary_types
dependencies:
  unsafe_extension: any
dev_dependencies:
  unittest: any
